init:
 - appveyor version
 - sh: echo $APPVEYOR_BUILD_WORKER_CLOUD
 - sh: echo $APPVEYOR_BUILD_WORKER_IMAGE
 
stack:
  - %RUBY_STACK%

test_script:
- sh: |
    command -v ruby
    ruby --version
    if [[ $(ruby --version 2>&1) =~ ruby\ ${APPVEYOR_STACK_RUBY} ]]; then
        echo "Version is Correct"
    else
        echo "[ERROR] Version of Ruby is incorrect!" 1>&2;
        exit 2;
    fi

build: off
