init:
 - appveyor version
 - sh: echo $APPVEYOR_BUILD_WORKER_CLOUD
 - sh: echo $APPVEYOR_BUILD_WORKER_IMAGE
 - sh: sudo sh -c "echo 'export PATH=~/.rbenv/shims:$PATH' > /etc/profile.d/test.sh"
 - sh: cat /etc/profile.d/test.sh
 - sh: source /etc/profile.d/test.sh
 - sh: echo $PATH
 #- sh: export PATH=~/.rbenv/shims:$PATH
 - sh: curl -sL https://gist.githubusercontent.com/OwenMcDonnell/c63da7c5ba8508c219df01a503f57565/raw/f536aefc570e4566985d39e1e916c74291c97dcc/rvm > /var/tmp/rvm
 - sh: sudo cp /var/tmp/rvm /usr/bin/rvm
 - sh: sudo chmod +x /usr/bin/rvm
 #- sh: ~/.rbenv/bin/rbenv versions
install:
 - sh: echo $PATH
stack:
  - '${RUBY_STACK}'

test_script:
- sh: |
    command -v ruby
    ruby --version
    if [[ $(ruby --version 2>&1) =~ ruby\ ${APPVEYOR_STACK_RUBY} ]]; then
        echo "Version is Correct"
    else
        echo "[ERROR] Version of Ruby is incorrect!" 1>&2;
        exit 2;
    fi

build: off
